apiVersion: v1
kind: Service
metadata:
  name: {{ include "heimdall.fullname" . }}-postgresql
  labels:
    {{- include "heimdall.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: {{ .Values.postgres.service.type }}
  ports:
  - name: tcp-postgresql
    targetPort: tcp-postgresql
    port: {{ .Values.postgres.service.port }}
    protocol: TCP
  selector:
    {{- include "heimdall.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql