apiVersion: v1
kind: Secret
metadata:
  name: {{ include "heimdall.fullname" . }}-secret
data:
  databaseUsername: {{ .Values.postgres.user | b64enc | quote }}
  databasePassword: {{ .Values.postgres.password | b64enc | quote }}
  jwt: {{ .Values.heimdall.jwtSecret | default (randAlphaNum 64) | b64enc | quote }}
  api: {{ .Values.heimdall.apiKeySecret | default (randAlphaNum 64) | b64enc | quote }}